services:
  - type: web
    name: django-istat-deploy
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        # custom domain (es. is-a.dev): ".onrender.com,djangoistat.is-a.dev"
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health/
    autoDeploy: true
